script:
  - id: script_1
    mode: queued
    parameters:
      light_wanted_state: bool
    then:
      if:
        condition:
          - lambda: |- 
              return light_wanted_state;
        then:
          if:
            condition:
              - lambda: |-
                  return id(light_1).state == false;
            then:
              - switch.turn_on: relay_1
              - delay: 200ms
              - switch.turn_off: relay_1
              - delay: 550ms
        else:
          if:
            condition:
              - lambda: |-
                  return id(light_1).state == true;
            then:
              - switch.turn_on: relay_1
              - delay: 200ms
              - switch.turn_off: relay_1
              - delay: 550ms
  - id: script_2
    mode: queued
    parameters:
      light_wanted_state: bool
    then:
      if:
        condition:
          - lambda: |-
              return light_wanted_state;
        then:
          if:
            condition:
              - lambda: |-
                  return id(light_2).state == false;
            then:
              - switch.turn_on: relay_2
              - delay: 200ms
              - switch.turn_off: relay_2
              - delay: 550ms
        else:
          if:
            condition:
              - lambda: |-
                  return id(light_2).state == true;
            then:
              - switch.turn_on: relay_2
              - delay: 200ms
              - switch.turn_off: relay_2
              - delay: 550ms
  - id: script_3
    mode: queued
    parameters:
      light_wanted_state: bool
    then:
      if:
        condition:
          - lambda: |-
              return light_wanted_state;
        then:
          if:
            condition:
              - lambda: |-
                  return id(light_3).state == false;
            then:
              - switch.turn_on: relay_3
              - delay: 200ms
              - switch.turn_off: relay_3
              - delay: 550ms
        else:
          if:
            condition:
              - lambda: |-
                  return id(light_3).state == true;
            then:
              - switch.turn_on: relay_3
              - delay: 200ms
              - switch.turn_off: relay_3
              - delay: 550ms
  - id: script_4
    mode: queued
    parameters:
      light_wanted_state: bool
    then:
      if:
        condition:
          - lambda: |-
              return light_wanted_state;
        then:
          if:
            condition:
              - lambda: |-
                  return id(light_4).state == false;
            then:
              - switch.turn_on: relay_4
              - delay: 200ms
              - switch.turn_off: relay_4
              - delay: 550ms
        else:
          if:
            condition:
              - lambda: |-
                  return id(light_4).state == true;
            then:
              - switch.turn_on: relay_4
              - delay: 200ms
              - switch.turn_off: relay_4
              - delay: 550ms
  - id: script_5
    mode: queued
    parameters:
      light_wanted_state: bool
    then:
      if:
        condition:
          - lambda: |-
              return light_wanted_state;
        then:
          if:
            condition:
              - lambda: |-
                  return id(light_5).state == false;
            then:
              - switch.turn_on: relay_5
              - delay: 200ms
              - switch.turn_off: relay_5
              - delay: 550ms
        else:
          if:
            condition:
              - lambda: |-
                  return id(light_5).state == true;
            then:
              - switch.turn_on: relay_5
              - delay: 200ms
              - switch.turn_off: relay_5
              - delay: 550ms
  - id: script_6
    mode: queued
    parameters:
      light_wanted_state: bool
    then:
      if:
        condition:
          - lambda: |-
              return light_wanted_state;
        then:
          if:
            condition:
              - lambda: |-
                  return id(light_6).state == false;
            then:
              - switch.turn_on: relay_6
              - delay: 200ms
              - switch.turn_off: relay_6
              - delay: 550ms
        else:
          if:
            condition:
              - lambda: |-
                  return id(light_6).state == true;
            then:
              - switch.turn_on: relay_6
              - delay: 200ms
              - switch.turn_off: relay_6
              - delay: 550ms
  - id: script_7
    mode: queued
    parameters:
      light_wanted_state: bool
    then:
      if:
        condition:
          - lambda: |-
              return light_wanted_state;
        then:
          if:
            condition:
              - lambda: |-
                  return id(light_7).state == false;
            then:
              - switch.turn_on: relay_7
              - delay: 200ms
              - switch.turn_off: relay_7
              - delay: 550ms
        else:
          if:
            condition:
              - lambda: |-
                  return id(light_7).state == true;
            then:
              - switch.turn_on: relay_7
              - delay: 200ms
              - switch.turn_off: relay_7
              - delay: 550ms
  - id: script_8
    mode: queued
    parameters:
      light_wanted_state: bool
    then:
      if:
        condition:
          - lambda: |-
              return light_wanted_state;
        then:
          if:
            condition:
              - lambda: |-
                  return id(light_8).state == false;
            then:
              - switch.turn_on: relay_8
              - delay: 200ms
              - switch.turn_off: relay_8
              - delay: 550ms
        else:
          if:
            condition:
              - lambda: |-
                  return id(light_8).state == true;
            then:
              - switch.turn_on: relay_8
              - delay: 200ms
              - switch.turn_off: relay_8
              - delay: 550ms

switch:
  ###### RELAYS #########
  - platform: gpio
    name: "Relay_1"
    pin: 13
    id: relay_1
    internal: $hide_outputs
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Relay_2"
    pin: 12
    id: relay_2
    internal: $hide_outputs
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Relay_3"
    pin: 4
    id: relay_3
    internal: $hide_outputs
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Relay_4"
    pin: 27
    id: relay_4
    internal: $hide_outputs
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Relay_5"
    id: relay_5
    internal: $hide_outputs
    restore_mode: RESTORE_DEFAULT_OFF
    pin: 26
  - platform: gpio
    name: "Relay_6"
    pin: 25
    internal: $hide_outputs
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay_6
  - platform: gpio
    name: "Relay_7"
    pin: 33
    id: relay_7
    internal: $hide_outputs
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Relay_8"
    pin: 32
    id: relay_8
    internal: $hide_outputs
    restore_mode: RESTORE_DEFAULT_OFF
  ###### Virtual switches ########
  - platform: template
    name: "light_1"
    id: light_1
    lambda: |-
      if (id(input_1).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: DISABLED
    turn_on_action:
      - script.execute:
          id: script_1
          light_wanted_state: true
    turn_off_action:
      - script.execute:
          id: script_1
          light_wanted_state: false
  - platform: template
    name: "light_2"
    id: light_2
    lambda: |-
      if (id(input_2).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: DISABLED
    turn_on_action:
      - script.execute:
          id: script_2
          light_wanted_state: true
    turn_off_action:
      - script.execute:
          id: script_2
          light_wanted_state: false
  - platform: template
    name: "light_3"
    id: light_3
    lambda: |-
      if (id(input_3).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: DISABLED
    turn_on_action:
      - script.execute:
          id: script_3
          light_wanted_state: true
    turn_off_action:
      - script.execute:
          id: script_3
          light_wanted_state: false
  - platform: template
    name: "light_4"
    id: light_4
    lambda: |-
      if (id(input_4).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: DISABLED
    turn_on_action:
      - script.execute:
          id: script_4
          light_wanted_state: true
    turn_off_action:
      - script.execute:
          id: script_4
          light_wanted_state: false
  - platform: template
    name: "light_5"
    id: light_5
    lambda: |-
      if (id(input_5).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: DISABLED
    turn_on_action:
      - script.execute:
          id: script_5
          light_wanted_state: true
    turn_off_action:
      - script.execute:
          id: script_5
          light_wanted_state: false
  - platform: template
    name: "light_6"
    id: light_6
    lambda: |-
      if (id(input_6).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: DISABLED
    turn_on_action:
      - script.execute:
          id: script_6
          light_wanted_state: true
    turn_off_action:
      - script.execute:
          id: script_6
          light_wanted_state: false
  - platform: template
    name: "light_7"
    id: light_7
    lambda: |-
      if (id(input_7).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: DISABLED
    turn_on_action:
      - script.execute:
          id: script_7
          light_wanted_state: true
    turn_off_action:
      - script.execute:
          id: script_7
          light_wanted_state: false
  - platform: template
    name: "light_8"
    id: light_8
    lambda: |-
      if (id(input_8).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: DISABLED
    turn_on_action:
      - script.execute:
          id: script_8
          light_wanted_state: true
    turn_off_action:
      - script.execute:
          id: script_8
          light_wanted_state: false

binary_sensor:
  - platform: gpio
    pin: 14
    id: input_1
    name: "Input_1"
    internal: $hide_inputs
    device_class: power
    filters:
      - delayed_on: 400ms
  - platform: gpio
    pin: 16
    id: input_2
    name: "Input_2"
    internal: $hide_inputs
    device_class: power
    filters:
      - delayed_on: 400ms
  - platform: gpio
    pin: 17
    id: input_3
    name: "Input_3"
    internal: $hide_inputs
    device_class: power
    filters:
      - delayed_on: 400ms
  - platform: gpio
    pin: 18
    name: "Input_4"
    id: input_4
    internal: $hide_inputs
    device_class: power
    filters:
      - delayed_on: 400ms
  - platform: gpio
    pin: 19
    name: "Input_5"
    id: input_5
    internal: $hide_inputs
    device_class: power
    filters:
      - delayed_on: 400ms
  - platform: gpio
    pin: 21
    name: "Input_6"
    id: input_6
    internal: $hide_inputs
    device_class: power
    filters:
      - delayed_on: 400ms
  - platform: gpio
    pin: 22
    name: "Input_7"
    id: input_7
    internal: $hide_inputs
    device_class: power
    filters:
      - delayed_on: 400ms
  - platform: gpio
    pin: 23
    id: input_8
    internal: $hide_inputs
    name: "Input_8"
    device_class: power
    filters:
      - delayed_on: 400ms
