substitutions:
  relay_pulse_duration: "50ms"   # Pulse duration for latching relay
  state_check_delay: "50ms"     # Delay before checking if toggle succeeded
  on_off_delay: "0ms"

globals:
  - id: relay_lock  # Ensures only one relay is energized at a time
    type: bool
    restore_value: no
    initial_value: 'false'

switch:
  - platform: restart
    name: "Restart device"

packages:
  light_1: !include
    file: channel.yaml
    vars:
      n: "1"
      relay_pin: "13"
      input_pin: "14"
      relay_restore_mode: "RESTORE_DEFAULT_OFF"
  light_2: !include
    file: channel.yaml
    vars:
      n: "2"
      relay_pin: "12"
      input_pin: "16"
      relay_restore_mode: "ALWAYS_OFF"
  light_3: !include
    file: channel.yaml
    vars:
      n: "3"
      relay_pin: "4"
      input_pin: "17"
      relay_restore_mode: "RESTORE_DEFAULT_OFF"
  light_4: !include
    file: channel.yaml
    vars:
      n: "4"
      relay_pin: "27"
      input_pin: "18"
      relay_restore_mode: "RESTORE_DEFAULT_OFF"
  light_5: !include
    file: channel.yaml
    vars:
      n: "5"
      relay_pin: "26"
      input_pin: "19"
      relay_restore_mode: "RESTORE_DEFAULT_OFF"
  light_6: !include
    file: channel.yaml
    vars:
      n: "6"
      relay_pin: "25"
      input_pin: "21"
      relay_restore_mode: "RESTORE_DEFAULT_OFF"
  light_7: !include
    file: channel.yaml
    vars:
      n: "7"
      relay_pin: "33"
      input_pin: "22"
      relay_restore_mode: "RESTORE_DEFAULT_OFF"
  light_8: !include
    file: channel.yaml
    vars:
      n: "8"
      relay_pin: "32"
      input_pin: "23"
      relay_restore_mode: "RESTORE_DEFAULT_OFF"
